---
- name: composer / download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: "/tmp/composer-setup.php"

- name: composer / install composer
  block:
  - name: composer / composer-setup
    command: "php composer-setup.php"
    args:
      chdir: "/tmp"

  - name: composer / remove composer-setup.php
    file:
      state: absent
      path:  "/tmp/composer-setup.php"

- name: commposer / move composer.phar
  command: mv "/tmp/composer.phar" "{{ composer_path }}"
